#
# This is free software, lisence use MIT.
# 参考以下各位大佬的action文件和实现思路,结合自身需求,顺便学习了一下action规范，写了一个基于lean的openwrt源码自动化构建镜像的配置
# Copyright (C) 2019 P3TERX <https://p3terx.com> <https://github.com/P3TERX/Actions-OpenWrt>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com> <https://github.com/KFERMercer/OpenWrt-CI>
# Copyright (C) 2019 esirplayground <https://www.youtube.com/c/esirplayground> <https://github.com/esirplayground/AutoBuild-OpenWrt>
# 
# 

name: Lean-OpenWrt-CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  #push:
    #branches:
      #- master
  
  # UTC 12:00 (UTC+8 20:00),every friday
  schedule:
    - cron: 0 12 1 1 *
  watch:
    types: [started]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Prepare build environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          df -h
          docker rmi `docker images -q`
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-mark hold grub-efi-amd64-signed
          sudo -E apt update
          df -h
          sudo -E apt -y purge azure-cli* docker* ghc* zulu* llvm* firefox google* dotnet* powershell* openjdk* mysql* php* mongodb* dotnet* snap*
          sudo -E apt -y full-upgrade
          sudo -E apt -y install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool llvm lrzsz msmtp ninja-build p7zip p7zip-full patch pkgconf python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          sudo -E systemctl daemon-reload
          sudo -E apt -y autoremove --purge
          sudo -E apt clean
          sudo -E timedatectl set-timezone "Asia/Shanghai"
          df -h

      - name: Clone source code
        env: 
          REPO_URL: https://github.com/coolsnowwolf/lede
          REPO_BRANCH: master
        run: git clone $REPO_URL -b $REPO_BRANCH openwrt

      - name: Update and Install feeds
        working-directory: ./openwrt
        run: |
          sed -i 's/#src-git helloworld/src-git helloworld/g' ./feeds.conf.default
          echo "=========================="
          echo "feeds.conf.default"
          echo "=========================="
          cat ./feeds.conf.default
          echo "=========================="
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          df -h
      - name: Run custom command before compile
        env:
          BEFORE_SCRIPT: 'customize_before_compile.sh'		  
        run: |
          [ -e $BEFORE_SCRIPT ] && chmod +x ./$BEFORE_SCRIPT && ./$BEFORE_SCRIPT

      - name: Generate configuration file
        env:
            CUSTOM_CONFIG_FILE: 'myconfig.diff'
        run: |
          [ -e $CUSTOM_CONFIG_FILE ] && mv $CUSTOM_CONFIG_FILE ./openwrt/.config
          cd openwrt && make defconfig

      - name: Compile firmware
        working-directory: ./openwrt
        run: |
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          make -j8 download V=s
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h

      - name: Run custom command after compile
        env:
          AFTER_SCRIPT: 'customize_after_compile.sh'		  
        run: |
          [ -e $AFTER_SCRIPT ] && chmod +x ./$AFTER_SCRIPT && ./$AFTER_SCRIPT

      - name: Prepare artifact
        run: |
          find ./openwrt/bin/targets/ -type d -name "packages" | xargs rm -rf {}
          find ./openwrt/bin/targets/ -type f -name "*.img" | xargs rm -rf 

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Lean-OpenWrt-x64
          path: ./openwrt/bin/targets/x86/64
